 OSL iter=  1 iper=  6 ileq= 38 probstat=  0 probstat2=  3
 OSL iter=  2 iper=  6 ileq= 39 probstat=  0 probstat2=  3
 OSL iter=  3 iper=  6 ileq= 39 probstat=  0 probstat2=  3
 OSL iter=  7 iper=  6 ileq= 39 probstat=  0 probstat2=  3
 OSL iter= 12 iper=  6 ileq= 39 probstat=  0 probstat2=  3
 OSL iter= 16 iper=  6 ileq= 39 probstat=  0 probstat2=  3
 OSL iter= 22 iper=  6 ileq= 39 probstat=  0 probstat2=  3
