 OSL iter=  5 iper=  6 ileq=127 probstat=  0 probstat2=  3
 OSL iter= 13 iper=  6 ileq=127 probstat=  0 probstat2=  3
 OSL iter= 14 iper=  6 ileq=127 probstat=  0 probstat2=  3
 OSL iter= 15 iper=  6 ileq=127 probstat=  0 probstat2=  3
 OSL iter= 16 iper=  6 ileq=127 probstat=  0 probstat2=  3
 OSL iter= 17 iper=  6 ileq=127 probstat=  0 probstat2=  3
 OSL iter= 18 iper=  6 ileq=127 probstat=  0 probstat2=  3
 OSL iter= 19 iper=  6 ileq=127 probstat=  0 probstat2=  3
