 OSL iter=  1 iper=  6 ileq= 11 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  6 ileq= 13 probstat=  0 probstat2=  3
 OSL iter=  2 iper=  6 ileq= 13 probstat=  0 probstat2=  3
 OSL iter=  9 iper=  6 ileq= 11 probstat=  0 probstat2=  3
 OSL iter= 10 iper=  6 ileq= 11 probstat=  0 probstat2=  3
 OSL iter= 11 iper=  6 ileq= 11 probstat=  0 probstat2=  3
 OSL iter= 12 iper=  6 ileq= 11 probstat=  0 probstat2=  3
 OSL iter= 18 iper=  6 ileq= 11 probstat=  0 probstat2=  3
