 OSL iter=  1 iper=  1 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  2 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  5 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  2 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  2 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  3 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  3 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  3 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  4 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  4 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  5 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  5 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  6 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  8 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter= 10 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter= 10 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter= 12 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter= 12 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 12 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter= 13 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter= 13 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 14 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 NAO FOI POSSIVEL ALOCAR MEMORIA A VSOLUTION            0           151  
           1          5081             1
 NAO FOI POSSIVEL ALOCAR MEMORIA A VOBJECTIVE            0           151  
           2          5081             1
 NAO FOI POSSIVEL ALOCAR MEMORIA A VCOLRCOSTS            0           151  
           3          5081             1
 NAO FOI POSSIVEL ALOCAR MEMORIA A VROWDUALS            0           151  
           4          5898             1
 NAO FOI POSSIVEL ALOCAR MEMORIA A VROWACTS            0           151  
           5          5898             1
