 OSL iter=  1 iper=  1 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  2 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  5 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  2 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  3 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  4 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  4 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter=  5 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter=  7 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 11 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 14 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 14 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter= 16 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 16 iper=  4 ileq=  1 probstat=  0 probstat2=  3
 OSL iter= 17 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 20 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 21 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 22 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 23 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 OSL iter= 24 iper=  6 ileq=  8 probstat=  0 probstat2=  3
 NAO FOI POSSIVEL ALOCAR MEMORIA A VSOLUTION            0           151  
           1          5097             1
 NAO FOI POSSIVEL ALOCAR MEMORIA A VOBJECTIVE            0           151  
           2          5097             1
 NAO FOI POSSIVEL ALOCAR MEMORIA A VCOLRCOSTS            0           151  
           3          5097             1
 NAO FOI POSSIVEL ALOCAR MEMORIA A VROWDUALS            0           151  
           4          5916             1
 NAO FOI POSSIVEL ALOCAR MEMORIA A VROWACTS            0           151  
           5          5916             1
