 OSL iter=  1 iper=  6 ileq= 31 probstat=  0 probstat2=  3
 OSL iter=  1 iper=  6 ileq= 36 probstat=  0 probstat2=  3
 OSL iter=  2 iper=  6 ileq= 36 probstat=  0 probstat2=  3
 OSL iter=  3 iper=  6 ileq= 36 probstat=  0 probstat2=  3
 OSL iter=  4 iper=  6 ileq= 36 probstat=  0 probstat2=  3
 OSL iter=  5 iper=  6 ileq= 36 probstat=  0 probstat2=  3
 OSL iter=  6 iper=  6 ileq= 36 probstat=  0 probstat2=  3
 OSL iter=  7 iper=  6 ileq= 36 probstat=  0 probstat2=  3
